steps:
  - label: ':coverage: Test Prisma 2'
    trigger: 'prisma2-test'
  - label: ':flashlight: Publish Prisma 2'
    trigger: 'prisma2-publish'
    build:
      env:
        BUILDKITE_TAG: '${BUILDKITE_TAG}'
    if: |
      // Only run on master branch
      // More docs here https://buildkite.com/docs/pipelines/conditionals
      build.branch == 'master' || build.tag != null

  - wait
